### ISSUE TITLE
Configurar o e-mail para envio

### ISSUE THREAD

**Issue by MatheusAuditoris** [shivarajnaidu/simple-login-service-with-nodejs-mongodb#3]
Como faço para configurar o e-mail para enviar a autenticação não estou achando a função.

**Comment by yuvarajvemula** [comment]
You can find send mail here https://github.com/shivarajnaidu/simple-login-service-with-nodejs-mongodb/blob/master/app/lib/send-mail.js (I'm using Sendgrid as email provider)
